apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop
  region: ap-southeast-1
  version: "1.36"

managedNodeGroups:
  - name: spot1
    labels:
      role: spot
    instanceTypes: ["m5.large", "m5a.large", "m6i.large"]
    spot: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    privateNetworking: false
    subnets:
      - subnet-0cc67479094982fdf
      - subnet-0fcbf89630d3c64b3
      - subnet-0f54b0e3e082589d8
    volumeType: gp3
    volumeSize: 30
    tags:
      nodegroup-name: spot1
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true
